# Generated by Django 3.0.5 on 2025-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_hash',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
