# Generated by Django 5.2.1 on 2025-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0003_auto_20250419_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHashB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageHash',
            new_name='ImageHashA',
        ),
    ]
