# Generated by Django 5.2.1 on 2025-05-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0004_imagehashb_rename_imagehash_imagehasha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageHashA',
            new_name='ImageHashDBA',
        ),
        migrations.RenameModel(
            old_name='ImageHashB',
            new_name='ImageHashDBB',
        ),
    ]
