# Generated by Django 3.0.5 on 2025-05-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0005_rename_imagehasha_imagehashdba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dba_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.ImageHashDBA')),
                ('dbb_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.ImageHashDBB')),
            ],
            options={
                'unique_together': {('dba_hash', 'dbb_hash')},
            },
        ),
    ]
